services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ruta-segura-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
